[build]
  command = "npm run build:netlify"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_NETLIFY_CMS_ENABLED = "true"
  NEXT_PUBLIC_SITE_URL = "https://your-site-name.netlify.app"
  NODE_VERSION = "18.17.0"
  NETLIFY = "true"
  NODE_ENV = "production"
  BLOG_POSTS_DIRECTORY = "/opt/build/repo/public/_posts"

# Enable the Next.js Runtime for better performance
[build.processing]
  skip_processing = false
  
  # CSS processing settings
  [build.processing.css]
    bundle = true
    minify = true
  
  # JavaScript processing settings
  [build.processing.js]
    bundle = true
    minify = true
  
  # Image processing settings
  [build.processing.images]
    compress = true

# Handle Next.js routing properly
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects and rewrites 
[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {error = true}

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

# Cache optimization
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Ensure blog files are included in the build
[functions]
  included_files = ["_posts/**", "public/**"]
  node_bundler = "esbuild"

# Netlify CMS configuration
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block" 